browser=chrome
headless=false
base.url=https://automationexercise.com
implicit.wait=10
explicit.wait=20

platform=web

appium.server.url=http://127.0.0.1:4723
mobile.platform=android
android.device.name=emulator-5554
android.app.path=